# Generated by Django 5.1.2 on 2024-10-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_condition', models.CharField(max_length=255)),
                ('critical_date', models.DateField()),
                ('treatment_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabStaffDoctor',
            fields=[
                ('lab_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Patient', 'Patient'), ('Visitor', 'Visitor'), ('Doctor', 'Doctor'), ('Admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('guideline_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_effective', models.DateField()),
                ('critical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.criticalcase')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAvailability',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('available_units', models.IntegerField()),
                ('lab_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.labstaffdoctor')),
            ],
        ),
        migrations.CreateModel(
            name='Migrant',
            fields=[
                ('migrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('date_of_movement', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.patient')),
            ],
        ),
        migrations.AddField(
            model_name='criticalcase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.patient'),
        ),
        migrations.CreateModel(
            name='SampleCollected',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_date', models.DateField()),
                ('test_result', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('lab_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.labstaffdoctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabStaffContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=255)),
                ('lab_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.labstaffdoctor')),
            ],
            options={
                'unique_together': {('lab_staff', 'contact_info')},
            },
        ),
        migrations.CreateModel(
            name='PatientContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.patient')),
            ],
            options={
                'unique_together': {('patient', 'contact_info')},
            },
        ),
        migrations.CreateModel(
            name='PatientSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.patient')),
            ],
            options={
                'unique_together': {('patient', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=255)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.samplecollected')),
            ],
            options={
                'unique_together': {('sample', 'sample_type')},
            },
        ),
    ]
