# Generated by Django 5.1.2 on 2024-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_role_delete_labstaffcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_info',
            field=models.CharField(default='1234', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PatientContactInfo',
        ),
    ]
